question_data = [
    {"text": "The common software-programming acronym 'I18N' comes from the term 'Interlocalization'.",
     "answer": "False"},
    {"text": "FLAC stands for 'Free Lossless Audio Condenser.",
     "answer": "False"},
    {"text": "The very first recorded computer 'bug' was a moth found inside a Harvard Mark II computer.",
     "answer": "True"},
    {"text": "Linus Torvalds created Linux and Git.",
     "answer": "True"},
    {"text": "Pointers were not used in the original C programming language; they were added later on in C++.",
     "answer": "False"},
    {"text": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
     "answer": "True"},
    {"text": "RAM stands for Random Access Memory.",
     "answer": "True"},
    {"text": "Ada Lovelace is often considered the first computer programmer.",
     "answer": "True"},
    {"text": "MacOS is based on Linux.",
     "answer": "False"},
    {"text": "The open source program Redis is a relational database server.",
     "answer": "False"},
    {"text": "DHCP stands for Dynamic Host Configuration Port.",
     "answer": "False"},
    {"text": "In most programming languages, the operator ++ is equivalent to the statement '+= 1'.",
     "answer": "True"},
    {"text": "Time on Computers is measured via the EPOX System.",
     "answer": "False"},
    {"text": "The Windows 7 operating system has six main editions.",
     "answer": "True"},
    {"text": "The first dual-core CPU was the Intel Pentium D.",
     "answer": "False"},
    {"text": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
     "answer": "False"},
    {"text": "It's not possible to format a write-protected DVD-R Hard Disk.",
     "answer": "True"},
    {"text": "Linux was first created as an alternative to Windows XP.",
     "answer": "False"},
    {"text": "Android versions are named in alphabetical order.",
     "answer": "True"},
    {"text": "The Python programming language gets its name from the British comedy group 'Monty Python'.",
     "answer": "True"}]
